[project]
name = "leapfrogai-backend-whisper"
version = "0.1.0"
description = "Whisper backend for LeapfrogAI"
dependencies = [
    "leapfrogai~=0.3.3",
    "openai-whisper>=20230918",
]
readme = "README.md"
requires-python = ">=3.11.4"

[project.optional-dependencies]
dev = ["pip-tools", "pytest", "black", "isort"]

[tool.pip-tools]
generate-hashes = false