[project]
name = "leapfrogai-backend-whisper"
version = "0.4.0"
description = "Whisper backend for LeapfrogAI"
dependencies = [
    "leapfrogai >= 0.4.0",
    "openai-whisper >= 20230918",
    "ffmpeg >= 1.4",
    "ctranslate2",
    "faster-whisper",
    "transformers",
]
requires-python = ">=3.11.4"
readme = "README.md"

[project.optional-dependencies]
dev = ["pip-tools", "pytest", "black", "isort"]

[tool.pip-tools]
generate-hashes = true
