package:
  create:
    set:
      name: whisper
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/whisper"
      image_version: 0.5.0
    max_package_size: "1000000000"
  deploy:
    set:
      name: whisper
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/whisper"
      image_version: 0.5.0
      limits_cpu: 1
      limits_memory: 20Gi
      limits_gpu: "###ZARF_VAR_NUMBER_OF_GPUS###"
      requests_cpu: 1
      requests_memory: 4Gi
      requests_gpu: "###ZARF_VAR_NUMBER_OF_GPUS###"
