package:
  create:
    set:
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/whisper"
      image_version: 0.4.0
      name: whisper
    max_package_size: "1000000000"
  deploy:
    set:
      limits_cpu: 0
      limits_memory: 0
      limits_gpu: 0
      requests_cpu: 0
      requests_memory: 0
      requests_gpu: 0
      name: whisper
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/whisper"
      image_version: 0.4.0
