package:
  create:
    set:
      name: whisper
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/whisper"
      image_version: 0.5.0
    max_package_size: "1000000000"
  deploy:
    set:
      name: whisper
      image_repository: "ghcr.io/defenseunicorns/leapfrogai/whisper"
      image_version: 0.5.0
