name: e2e
on: [pull_request]

jobs:
  e2e:
    runs-on: ai-ubuntu-big-boy-8-core

    steps:
        - name: Checkout Repo
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: Setup Python
          uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c #v5.0.0
          with:
            python-version-file: 'pyproject.toml'

        # TODO @JPERRY: This is installing a lot more than we need...
        #               We only need a minor subset of these deps for running the tests
        - name: Install Python Deps
          run: make requirements-dev

        - name: Install UDS-CLI
          run: |
            wget https://github.com/defenseunicorns/uds-cli/releases/download/v0.9.2/uds-cli_v0.9.2_Linux_amd64
            chmod +x uds-cli_v0.9.2_Linux_amd64
            sudo mv uds-cli_v0.9.2_Linux_amd64 /usr/local/bin/uds

        - name: Setup K3D
          run: |
            wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.6.0 bash
          
        - name: Create UDS Cluster
          run: |
            uds deploy oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core-istio-dev:0.13.1 -l=trace --confirm

        #TODO @JPERRY: Consider deploying this as part of a bundle
        - name: Install lfai-api 
          run: |
            uds zarf package deploy oci://ghcr.io/defenseunicorns/packages/leapfrogai-api:v0.5.1 --confirm

        # TODO @JPERRY: This is going to need to build the image in the future.
        #     : That is going to be annoying...
        - name: Build Whisper Zarf Package
          run: |
            uds zarf package create . --set=IMAGE_VERSION=0.5.0-amd64 --confirm

        # TODO @JPERRY:  Consider deploying this as part of a bundle
        - name: Install Whisper Backend
          run: |
            uds zarf package deploy zarf-package-whisper-amd64-*.tar.zst --confirm

        - name: Run Tests
          run: |
            python -m pytest . -v